---
spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
cds:
  security:
    mock:
      users:
        admin:
          password: admin
          roles[0]: admin
        user:
          password: user
    log-potentially-sensitive: true
  data-source:
    auto-config:
      enabled: false
logging:
  level:
    com:
      sap:
        cds: DEBUG
